services:
  web:
    build: .
    volumes:
      - 'staticfiles:/movie_admin/staticfiles'
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: 'postgres:13'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=movies
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    expose:
      - 5432
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
  
  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    volumes_from:
      - web
    env_file:
      - ./.env
    depends_on:
    ports:
      - '80:80'
    depends_on:
      - web

volumes:
  postgres_data: null
  staticfiles: null


networks:
  default:
    driver: bridge
