# Generated by Django 3.1.2 on 2020-10-11 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION "uuid-ossp";'),
        migrations.RunSQL('ALTER TABLE "movies_filmwork_genres" '  # FlimWorkGenres  django генерирует автоматически
                          'ALTER COLUMN "id" DROP DEFAULT, '
                          'ALTER COLUMN "id" TYPE uuid USING (uuid_generate_v4()), '
                          'ALTER COLUMN "id" SET DEFAULT uuid_generate_v4();'),
        migrations.RunSQL('ALTER TABLE "movies_filmwork_genres" '
                          'ADD COLUMN "created_at" timestamp with time zone NOT NULL DEFAULT NOW();'),
    ]
